services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
    networks:
      - app-network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:3.13.2-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - ./rabbit:/var/lib/rabbitmq
    restart: always
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
  api-gateway:
    build:
      context: api-gateway
    container_name: api-gateway
    hostname: api-gateway
    environment:
      JOKE_SERVICE_URL: "http://chucknorris-service:8001"
    ports:
      - 8000:8000
    expose:
      - 8000
    networks:
      - app-network
    depends_on:
      - chucknorris-service
  chucknorris-service:
    build:
      context: chucknorris-service
    container_name: chucknorris-service
    hostname: chucknorris-service
    environment:
      RABBIT_CONNECTION_STRING: 'amqp://user:password@rabbitmq:5672'
    ports:
      - 8001:8001
    expose:
      - 8001
    networks:
      - app-network
    depends_on:
      - rabbitmq
  notification-service:
    build:
      context: notification-service
    container_name: notification-service
    hostname: notification-service
    environment:
      RABBIT_CONNECTION_STRING: 'amqp://user:password@rabbitmq:5672'
    ports:
      - 8002:8002
    expose:
      - 8002
    networks:
      - app-network
    depends_on:
      - rabbitmq
networks:
  app-network:
    driver: bridge
volumes:
    prometheus_data: {}
    grafana_data: {}