global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8000"]
  - job_name: "chucknorris-service"
    static_configs:
      - targets: ["chucknorris-service:8001"]
  - job_name: "notification-service"
    static_configs:
      - targets: [ "notification-service:8002" ]
#  - job_name: "rabbitmq"
#    static_configs:
#      - targets: [ "rabbitmq:15692" ]
  - job_name: "rabbitmq_details"
    metrics_path: /metrics/per-object
    static_configs:
      - targets: [ "rabbitmq:15692" ]
