{
 "title": "Chuck Norris Dashboard",
 "time": { "from": "2024-05-17T23:02:12.322Z", "to": "2024-05-17T23:04:22.502Z" },
 "panels": [
  { "title": "Send Fact(Async)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API request - E2E",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(api_request_async[$__interval])) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "API request p(95) - By Service",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(api_request{quantile=\"0.95\"}[$__interval])",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "rate(send_notification{quantile=\"0.95\"}[$__interval])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Error counter - 500",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "round(increase(api_request_count{statusCode=\"500\"}[$__interval]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "API request - Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "round(increase(api_request_async_count[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of acked messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "round(increase(rabbitmq_channel_messages_delivered_ack_total{queue=\"notifications\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of pending messages in queue",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"notifications\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}